#!/usr/bin/env sh
set -e

# Verify that python3 is installed
if ! [ -x "$(command -v python3)" ]; then
  echo 'Error: python3 is not installed.' >&2
  exit 1
fi

SCRIPT_PATH=$(python3 -c "import os; print(os.path.realpath(os.path.dirname('$0')))")

if [ ! -d ".pyenv" ]; then
  python3 -m venv $SCRIPT_PATH/.pyenv
fi

. $SCRIPT_PATH/.pyenv/bin/activate 2>&1 > /dev/null
pip install -qU pip
pip install -qe $SCRIPT_PATH/src

runbot $@
